INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (1,'Драма');
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (2,'Мультфильм');
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (3,'Фэнтази');
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (4,'Приключения');
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (5,'Фантастика');
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (6,'Комедия');

INSERT INTO PUBLIC.MPA (MPA_ID, NAME, DESCRIPTION) VALUES (1,'R', 'Детям до 17 лет обязательно присутствие родителей');
INSERT INTO PUBLIC.MPA (MPA_ID, NAME, DESCRIPTION) VALUES (2,'PG', 'Рекомендуется присутствие родителей');
INSERT INTO PUBLIC.MPA (MPA_ID, NAME, DESCRIPTION) VALUES (3,'PG-13', 'Детям до 13 лет просмотр не желателен');

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(1, 'Тайна Коко','Юный музыкант Мигель попадает в мир мертвых. Трогательная история о любви без границ, получившая два «Оскара»', '2017-03-12', 105, 2);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (2,1);

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(2, 'Властелин колец: Возвращение короля','«There can be no triumph without loss. No victory without suffering. No freedom without sacrifice»', '2003-04-11', 201, 3);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (1,2);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (3,2);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (4,2);

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(3, 'Интерстеллар','«Следующий шаг человечества станет величайшим»', '2014-05-21', 169, 3);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (1,3);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (5,3);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (4,3);

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(4, 'Назад в будущее','Безумный ученый и 17-летний оболтус тестируют машину времени, наводя шороху в 1950-х. Классика кинофантастики', '1985-05-01', 116, 2);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (4,4);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (5,4);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (6,4);

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(5,'Зеленая миля','В тюрьме для смертников появляется заключенный с божественным даром. Мистическая драма по роману Стивена Кинга', '1999-01-01', 189, 1);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (1,5);

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(6,'Список Шиндлера','История немецкого промышленника, спасшего тысячи жизней во время Холокоста. Драма Стивена Спилберга', '1993-11-11', 195, 1);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (1,6);

INSERT INTO PUBLIC.FILMS(FILM_ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA_ID) VALUES(7, 'Побег из Шоушенка','Страх - это кандалы. Надежда - это свобода', '1994-02-02', 142, 1);
INSERT INTO PUBLIC.GENRE_REG (GENRE_ID, FILM_ID) VALUES (1,7);

INSERT INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (1, 'dinozavr@yandex.ru', 'dino', 'Антон', '1999-07-01');
INSERT INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (2, 'svekla@mail.ru', 'svekla', 'Светлана', '2000-08-11');
INSERT INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (3, 'papik@yandex.ru', 'don', 'Павел', '2001-11-21');
INSERT INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (4, 'java_god@microsoft.com', 'Billy', 'Билл', '1966-06-12');

INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (1,2);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (1,3);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (2,1);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (2,4);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (3,1);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (3,3);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (4,5);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (4,6);
INSERT INTO PUBLIC.LIKES (USER_ID,FILM_ID) VALUES (4,7);

INSERT INTO PUBLIC.FRIENDS_FLAG (FRIENDS_FLAG_ID, NAME_FLAG) VALUES (1, 'Друзья');
INSERT INTO PUBLIC.FRIENDS_FLAG (FRIENDS_FLAG_ID, NAME_FLAG) VALUES (2, 'Не подтверждён');

INSERT INTO PUBLIC.FRIENDS (FRIENDS_ID, FIRST_USER_ID, SECOND_USER_ID, FRIENDS_FLAG_ID) VALUES (1,1,2,1);
INSERT INTO PUBLIC.FRIENDS (FRIENDS_ID, FIRST_USER_ID, SECOND_USER_ID, FRIENDS_FLAG_ID) VALUES (2,1,3,1);
INSERT INTO PUBLIC.FRIENDS (FRIENDS_ID, FIRST_USER_ID, SECOND_USER_ID, FRIENDS_FLAG_ID) VALUES (3,1,4,2);
INSERT INTO PUBLIC.FRIENDS (FRIENDS_ID, FIRST_USER_ID, SECOND_USER_ID, FRIENDS_FLAG_ID) VALUES (4,2,1,1);
INSERT INTO PUBLIC.FRIENDS (FRIENDS_ID, FIRST_USER_ID, SECOND_USER_ID, FRIENDS_FLAG_ID) VALUES (5,3,4,1);
INSERT INTO PUBLIC.FRIENDS (FRIENDS_ID, FIRST_USER_ID, SECOND_USER_ID, FRIENDS_FLAG_ID) VALUES (6,4,3,1);