SET MODE POSTGRESQL;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (1,'Комедия') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (2,'Драма') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (3,'Мультфильм') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (4,'Триллер') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (5,'Документальный') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (6,'Боевик') ON CONFLICT DO NOTHING;

INSERT INTO PUBLIC.MPA (MPA_ID, NAME, DESCRIPTION) VALUES (1,'R', 'Детям до 17 лет обязательно присутствие родителей') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.MPA (MPA_ID, NAME, DESCRIPTION) VALUES (2,'PG', 'Рекомендуется присутствие родителей') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.MPA (MPA_ID, NAME, DESCRIPTION) VALUES (3,'PG-13', 'Детям до 13 лет просмотр не желателен') ON CONFLICT DO NOTHING;
