SET MODE POSTGRESQL;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (1,'Комедия') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (2,'Драма') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (3,'Мультфильм') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (4,'Триллер') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (5,'Документальный') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.GENRE  (GENRE_ID, NAME) VALUES (6,'Боевик') ON CONFLICT DO NOTHING;

INSERT INTO PUBLIC.MPA (MPA_ID, NAME) VALUES (1,'G') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.MPA (MPA_ID, NAME) VALUES (2,'PG') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.MPA (MPA_ID, NAME) VALUES (3,'PG-13') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.MPA (MPA_ID, NAME) VALUES (4,'R') ON CONFLICT DO NOTHING;
INSERT INTO PUBLIC.MPA (MPA_ID, NAME) VALUES (5,'NC-17') ON CONFLICT DO NOTHING;

